spring:
  profiles: peer1
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://ipcm-eureka-server:8761/
server:
  port: 8761
  wait-time-in-ms-when-sync-empty: 0
