my-eureka-cluster:
  port:
    peer1: 8761
    #peer2: 8762
  name: ipcm-eureka-cluster
---
spring:
  profiles: peer1
eureka:
  instance:
    hostname: ipcm-eureka-peer1
    appname: ${my-eureka-cluster.name}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://ipcm-eureka-peer1:8761/eureka
server:
  port: ${my-eureka-cluster.port.peer1}
